apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgd-execution
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgd-execution
  template:
    metadata:
      labels:
        app: bgd-execution
    spec:
      containers:
        - name: bgd-execution
          image: registry.gitlab.com/buildgrid/buildgrid/buildgrid:latest
          args:
            - server
            - start
            - -vvv
            - /etc/bgd/execution.yaml
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051
          volumeMounts:
            - mountPath: /etc/bgd
              name: bgd-exec-config
      volumes:
        - name: bgd-exec-config
          configMap:
            name: bgd-execution-conf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgd-bot
spec:
  replicas: 20
  selector:
    matchLabels:
      app: bgd-execution
  template:
    metadata:
      labels:
        app: bgd-execution
    spec:
      containers:
        - name: bgd-bot
          image: registry.gitlab.com/buildgrid/buildgrid/buildgrid:latest
          args:
            - bot
            - --remote=http://bgd-execution:50051
            - --instance-name=buildgrid
            - -vvv
            - host-tools
          imagePullPolicy: IfNotPresent
